title = "Alogrithm"
content = """
主要用于记录一些自己平时用到的一些比较有意思的算法，但并不是很难得那种。
另外 NOIP 提高组用到的基础算法我就不收录了，意义不大。
"""

[[groups]]
title = "Retry"

  [[groups.projects]]
  name = "Exponential backoff"
  website = "https://en.wikipedia.org/wiki/Exponential_backoff"
  content = """
指数回退算法，原本是用于计算机网络中避免冲突的解决方案，现在可以用于重发重试的通用解决方案。
"""
  createTime = 1_573_456_268_210
  updateTime = 1_573_456_268_210
