title = "DataBase"

[[groups]]
title = "Simple Datebase"

  [[groups.projects]]
  name = "jsonbox"
  repo = "https://github.com/vasanthv/jsonbox"
  content = """
> 一个非常简单在线免费数据库，可以非常方便的做一些原型出来。也可以作为 hackthon 的时候的数据库使用。
> 也正是因为简单，所以不推荐存储大量数据。
"""
  createTime = 1_568_964_767_757
  updateTime = 1_568_964_767_757
  description = "A Free HTTP based JSON storage."
