title = "Language"

[[groups]]
title = "Token Parser"

  [[groups.projects]]
  title = "PEG.js"
  repo = "https://github.com/pegjs/pegjs"
  createTime = 1_590_984_733_167
  description = "PEG.js: Parser generator for JavaScript"
  updateTime = 1_590_985_100_259
  website = "https://pegjs.org/"
