title = "Native App"
content = """
This page is relative to `Desktop App`, which can run on `Window`, `Mac` or `Linux`.

There have many framework to build `Desktop App`. Such as `Electron`, `NW.js`, etc.
"""

[[groups]]
title = "Electron"

  [[groups.projects]]
  name = "Photon"
  repo = "https://github.com/connors/photon"
  desc = "The fastest way to build beautiful Electron apps using simple HTML and CSS"
  content = """
> It's use `html/css` to build desktop components. Such as desktop app button, list, bars. Just like UI Kit in Swift.
> In another words, It can run without `Electron`. Because only html/css. Run In Any Browser.
"""
  createTime = 1_561_355_976_912
  updateTime = 1_561_355_976_912
  star = 9_025
