title = "Node Addon"

[[groups]]
title = "Rust - Node.js Binding"

  [[groups.projects]]
  name = "neon"
  repo = "https://github.com/neon-bindings/neon"
  desc = "Rust bindings for writing safe and fast native Node.js modules."
  createTime = 1_561_355_977_792
  updateTime = 1_561_355_977_792
  star = 3_462
