title = "Node Addon"

[[groups]]
title = "Rust - Node.js Binding"

  [[groups.projects]]
  name = "neon"
  repo = "https://github.com/neon-bindings/neon"
  createTime = 1_561_355_977_792
  updateTime = 1_567_146_169_717
  star = 3_462
  description = "Rust bindings for writing safe and fast native Node.js modules."
