title = "Others"

[[groups]]
title = "Useful Command"

  [[groups.projects]]
  name = "cash"
  repo = "https://github.com/dthree/cash"
  content = """
> I very like this. Because I can use unix-based command in window's `cmd` without install `cygwin`. Just to install a `cash`. But I'm a Macer :joy:.
> And you can replace `cygwin` with `cash`.
"""
  createTime = 1_561_355_978_627
  updateTime = 1_567_146_170_537
  star = 7_640
  description = ":dollar: Cross-platform Linux without the suck"

[[groups]]
title = "Antomation"

  [[groups.projects]]
  name = "RobotJS"
  repo = "https://github.com/octalmage/robotjs"
  content = """
> like `AutoHotkey`
"""
  createTime = 1_561_355_978_627
  updateTime = 1_567_146_170_537
  star = 8_001
  description = "Node.js Desktop Automation."
