title = "Tools for anything"

[[groups]]
title = "Scraffolding Tools"

  [[groups.projects]]
  name = "degit"
  repo = "https://github.com/Rich-Harris/degit#actions"
  content = """
> 很有意思的一个项目，不想 yo 那样复杂，你只需要提供一个 git 地址就可以了。
> 类似于 `git clone --depth=1` 但是更加强大和简单。从设计角度，我觉得这是一个非常简单高效几乎没有学习成本的脚手架。
"""
  createTime = 1_567_133_315_668
  updateTime = 1_567_146_171_340
  star = 944
  description = "Straightforward project scaffolding"
