title = "Tools for anything"

[[groups]]
title = "Scraffolding Tools"

  [[groups.projects]]
  name = "degit"
  repo = "https://github.com/Rich-Harris/degit#actions"
  content = """
> 很有意思的一个项目，不想 yo 那样复杂，你只需要提供一个 git 地址就可以了。
> 类似于 `git clone --depth=1` 但是更加强大和简单。从设计角度，我觉得这是一个非常简单高效几乎没有学习成本的脚手架。
"""
  createTime = 1_567_133_315_668
  updateTime = 1_567_146_171_340
  star = 944
  description = "Straightforward project scaffolding"

  [[groups.projects]]
  name = "plop"
  repo = "https://github.com/amwmedia/plop"
  content = """
> 只需要一个配置文件就可以非常灵活的定义好整个项目的文件模板。不需要去写 cli，简洁轻量又强大
> 但是缺点就是不适合跨项目使用，但是对于单一项目或者开源项目来讲，是非常方便的。
  """
  createTime = 1_580_716_362_830
  updateTime = 1_580_716_362_830
  description = "Consistency Made Simple"

[[groups]]
title = "NAT tools"

  [[groups.projects]]
  name = "localtunnel"
  repo = "https://github.com/localtunnel/localtunnel"
  website = "https://localtunnel.me"
  createTime = 1_571_646_238_150
  updateTime = 1_571_646_238_150
  description = "expose yourself"
