title = "Frontend Framework"

[[groups]]
title = "Css in js"

  [[groups.projects]]
  name = "linaria"
  repo = "https://github.com/callstack/linaria"
  website = "https://linaria.now.sh"
  content = """
> 零运行时真的很喜欢，也可以很好的平衡开发和运行效率，不过暂时不知道有什么缺点
"""
  createTime = 1_588_562_803_723
  updateTime = 1_588_562_803_723
  description = "Zero-runtime CSS in JS library"
