title = "Render Framework or Tools"

[[groups]]
title = "Layout"

  [[groups.projects]]
  name = "yoga"
  repo = "https://github.com/facebook/yoga"
  createTime = 1_591_513_424_567
  updateTime = 1_591_513_424_567
  description = "Yoga is a cross-platform layout engine which implements Flexbox. Follow https://twitter.com/yogalayout for updates."
  website = "https://yogalayout.com/"

  [[groups.projects]]
  name = "stretch"
  repo = "https://github.com/vislyhq/stretch"
  createTime = 1_591_513_424_568
  updateTime = 1_591_513_424_568
  description = "High performance flexbox implementation written in rust"
  website = "https://vislyhq.github.io/stretch/"
