title = "UI Framework"

[[groups]]
title = "CSS Library"

  [[groups.projects]]
  name = "classy-ui"
  repo = "https://github.com/cerebral/classy-ui"
  createTime = 1_590_474_789_175
  description = "An automatically optimized design system"
  updateTime = 1_590_474_809_991
  content = "原子化 UI 的高性能尝试"

[[groups]]
title = "Template"

  [[groups.projects]]
  name = "lit-html"
  repo = "https://github.com/Polymer/lit-html"
  content = """
> Polymer 出品，看起来很不错、很简单的一个渲染库，而且还有 patch update 的功能。
> 缺点就是库会比较大，毕竟为了实现 patch update 包含了一整个 html 的 parser。
"""
  createTime = 1_562_553_229_470
  updateTime = 1_567_146_164_001
  star = 4_980
  description = "An efficient, expressive, extensible HTML templating library for JavaScript."
