title = "CMS Website"

[[groups]]
title = "Static CMS"

  [[groups.projects]]
  name = "Forestry"
  website = "https://forestry.io/"
  content = """
> 看起来很不错的样子，解决了平时写博客必须要带着电脑的问题，以及无法在别人的电脑上写博客的问题
> 比较灵活的方案和方式，而且对个人免费，支持 hugo, jekyll, VuePress，但是不支持 hexo
"""
  createTime = 1_562_294_889_365
  updateTime = 1_567_146_172_177
  description = "Sync your Jekyll, Hugo or VuePress site. Your editors will love it and won’t realize they’re making commits."
